services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: temu_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - temu-webshop-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: temu/backend:latest
    restart: always
    depends_on:
      - db
    environment:
      # Damit Nest/TypeORM zur Laufzeit die DB findet:
      DB_HOST: db
      DB_PORT: '5432'
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_DATABASE: temu_db
    ports:
      - '3001:3001'
    networks:
      - temu-webshop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    image: temu/frontend:latest
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    ports:
      - '3000:3000'
    networks:
      - temu-webshop-network
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - temu-webshop-network

volumes:
  db_data:

networks:
  temu-webshop-network:
    driver: bridge


